cmake_minimum_required(VERSION 2.8)

foreach(libname ${CONAN_LIBS})
    find_library(${libname}_LIBRARY NAMES ${libname} PATHS ${CONAN_LIB_DIRS} NO_CMAKE_FIND_ROOT_PATH)
    set(FREETYPE_LIBRARY ${FREETYPE_LIBRARY} ${${libname}_LIBRARY})
endforeach(libname ${CONAN_LIBS})

set(FREETYPE_INCLUDE_DIRS ${CONAN_INCLUDE_DIRS})
set(FREETYPE_INCLUDE_DIR ${CONAN_INCLUDE_DIRS_FREETYPE})
set(FREETYPE_LIBRARIES ${CONAN_LIBS})

MESSAGE("** FREETYPE ALREADY FOUND BY CONAN!")
SET(FREETYPE_FOUND TRUE)
MESSAGE("** FOUND FREETYPE:  ${FREETYPE_LIBRARY}")
MESSAGE("** FOUND FREETYPE INCLUDE:  ${FREETYPE_INCLUDE_DIR}")

mark_as_advanced(FREETYPE_LIBRARY FREETYPE_INCLUDE_DIR)

set(FREETYPE_MAJOR_VERSION "2")
set(FREETYPE_MINOR_VERSION "9")
set(FREETYPE_PATCH_VERSION "0")
